version: '2'
services:
    redis_db:
        #build: ./
        build: ./3.0.1
        container_name: redis_cluster
        volumes:
            - "./cluster_conf:/data/redis"
        working_dir:
            /data/redis
        networks:
            redis_cluster:
              ipv4_address: 10.10.10.10
        ports:
            - "16479:6479"
            - "16480:6480"
            - "16481:6481"
            - "16482:6482"
            - "16483:6483"
            - "16484:6484"
            - "16485:6485"
            - "16486:6486"
            - "16487:6487"
        command:
            ["/bin/bash", "bin/start_redis_all.sh"]
networks:
    redis_cluster:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.10.10.0/24
              gateway: 10.10.10.1
